<?php
    /* @var $block \Swissup\Testimonials\Block\Widgets\Slider */
    $testimonials = $block->getTestimonials();
    if (!count($testimonials)) {
        return;
    }
?>

<div class="widget block testimonials-slider slides-5 ?>" data-content-type="testimonials" data-dataprovider-config='<?= $block->getDataProviderConfig() ?>'>
    <div class="block-content">
        <div class="swiper-container" data-mage-init='{"Swissup_Swiper/js/swiper": {"slidesPerView":"2","slidesToScroll":1,"freeMode":false,"loop":true,"spaceBetween":10,"navigation":{"nextEl":".swiper-button-next","prevEl":".swiper-button-prev"},"breakpoints":{"1024":{"slidesPerView":1}}}}'>
            <div class="swiper-wrapper">
            <?php foreach ($testimonials as $testimonial): ?>
                <figure class="testimonial swiper-slide">
                    <blockquote>
                        <?php if ($ratingPercent = $block->getRatingPercent($testimonial)): ?>
                        <div class="rating nobr">
                            <div class="review-ratings">
                                <div class="rating-summary item">
                                    <span class="label rating-label">
                                        <span><?= __('Rating') ?></span>
                                    </span>
                                    <div class="rating-result" title="<?= $ratingPercent ?>%">
                                        <span style="width:<?= $ratingPercent ?>%">
                                            <span><?= $ratingPercent ?>%</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php endif; ?>
                        <p class="testimonial-message"><?= $block->escapeHtml($testimonial->getMessage()); ?></p>

                        <?php if ($testimonial->getWebsite()): ?>
                            <a target="_blank" href="<?= $testimonial->getWebsite() ?>"><?= __('Full review') ?></a>
                        <?php endif; ?>

                        <div class="arrow"></div>
                    </blockquote>
                    <!-- <img src="<?= $block->getProfileImageUrl($testimonial) ?>" alt="Profile image" loading="lazy" /> -->
                    <div class="author">
                        <h5><?= $block->escapeHtml($testimonial->getName()) ?></h5> 
                        <?php if ($testimonial->getCompany()): ?>
                        <p><?= $block->escapeHtml($testimonial->getCompany()) ?></p>
                        <?php endif; ?>
                    </div>
                </figure>
            <?php endforeach; ?>
            </div>
            <div class="swiper-button-prev swiper-button-black"></div>
            <div class="swiper-button-next swiper-button-black"></div>
        </div>
    </div>
</div>
